### ISSUE TITLE
can not use UniRx in unity3d 5.6.X?

### ISSUE THREAD

**Issue by moto2002** [neuecc/UniRx#233]
Assets/Plugins/uFrame/UniRx/Scripts/UnityEngineBridge/MainThreadDispatcher.cs(274,35): error CS0176: Static member `UniRx.MainThreadDispatcher.StartCoroutine(System.Collections.IEnumerator)' cannot be accessed with an instance reference, qualify it with a type name instead

**Comment by NoxMortem** [comment]
I am using UniRX in UNity3d 5.6.0p3. Have you tried removing the package and importing it again?

**Comment by Chaser324** [comment]
I'm using UniRX in 5.6.1f1 without issue.

**Comment by renzihui** [comment]
@moto2002 
I guess you were using an old version of UniRx which had something like this

    Instance.StartCoroutine(routine)  

where Instance is class member while StartCoroutine is a static method. This did compile in pre 5.6 but not compile on 5.6 any more, if you don't want to upgrade UniRx, simply replace Instance with MainThreadDispatcher.

Those code had been removed and seems this issue could be closed.
